In [22]:

import numpy as np
from PIL import Image

In [23]:
def convolution(matrix, kernel, stride=(1, 1)):
    # Calculating the dimensions of the output matrix
    row = (matrix.shape[0] - kernel.shape[0]) // stride[0] + 1
    col = (matrix.shape[1] - kernel.shape[1]) // stride[1] + 1
    filtered_matrix = np.zeros(shape=(row, col))
    
    # Looping through the matrix with the given stride
    for i in range(0, row * stride[0], stride[0]):
        for j in range(0, col * stride[1], stride[1]):
            # Ensuring the kernel fits within the matrix boundaries
            current = matrix[i:i + kernel.shape[0], j:j + kernel.shape[1]]
            multiplication = np.sum(current * kernel)
            filtered_matrix[i // stride[0], j // stride[1]] = multiplication
    
    return filtered_matrix

**With matrix**

In [24]:
# Defining a 9x9 matrix with random values
#matrix = np.random.randint(0, 100, size=(9, 9))
#print("Input Matrix:\n", matrix)

# Defining a 3x3 kernel for demonstration
kernel_3x3 = np.array([[-1, -1, -1],
                       [-1, 0, -1],
                       [-1, -1, -1]])

# Defining a 5x5 kernel for demonstration
kernel_5x5 = np.array([[-1, -1, -1, -1, -1],
                       [-1, -1, -1, -1, -1],
                       [-1, -1, 0, -1, -1],
                       [-1, -1, -1, -1, -1],
                       [-1, -1, -1, -1, -1]])

**With real Image**

In [25]:
# Loading an image and convert it to grayscale
# Download the image
url = "https://pluspng.com/img-png/png-person-walking-2-person-3-person-1704.png"
response = requests.get(url)
#image_path = 'images/shutterstock_124681555-1869579152.jpg' # Replace with your image path
#image = Image.open(image_path).convert('L')

image = Image.open(BytesIO(response.content)).convert('L')


# Convert the image to a numpy array
matrix = np.array(image)


In [26]:

# Performing convolution with a stride of 1x1
filtered_matrix_3x3_stride_1 = convolution(matrix, kernel_3x3, stride=(1, 1))
print("3x3 Kernel with 1x1 Stride:\n", filtered_matrix_3x3_stride_1)
print()

# Performing convolution with a stride of 2x2
filtered_matrix_3x3_stride_2 = convolution(matrix, kernel_3x3, stride=(2, 2))
print("3x3 Kernel with 2x2 Stride:\n", filtered_matrix_3x3_stride_2)
print()

3x3 Kernel with 1x1 Stride:
 [[-417. -418. -420. ... -833. -837. -842.]
 [-423. -422. -420. ... -828. -832. -837.]
 [-427. -426. -421. ... -831. -834. -839.]
 ...
 [-545. -542. -536. ... -421. -418. -417.]
 [-554. -548. -536. ... -420. -419. -419.]
 [-553. -549. -541. ... -420. -421. -421.]]

3x3 Kernel with 2x2 Stride:
 [[-417. -420. -422. ... -842. -833. -837.]
 [-427. -421. -414. ... -839. -831. -834.]
 [-423. -420. -418. ... -848. -839. -843.]
 ...
 [-518. -524. -529. ... -422. -414. -418.]
 [-539. -532. -541. ... -422. -420. -418.]
 [-554. -536. -548. ... -421. -420. -419.]]



In [27]:
# Performing convolution with a stride of 1x1
filtered_matrix_5x5_stride_1 = convolution(matrix, kernel_5x5, stride=(1, 1))
print("5x5 Kernel with 1x1 Stride:\n", filtered_matrix_5x5_stride_1)
print()

# Performing convolution with a stride of 2x2
filtered_matrix_5x5_stride_2 = convolution(matrix, kernel_5x5, stride=(2, 2))
print("5x5 Kernel with 2x2 Stride:\n", filtered_matrix_5x5_stride_2)

5x5 Kernel with 1x1 Stride:
 [[-1263. -1261. -1259. ... -2508. -2508. -2516.]
 [-1268. -1263. -1257. ... -2508. -2508. -2515.]
 [-1268. -1263. -1257. ... -2509. -2509. -2516.]
 ...
 [-1600. -1607. -1611. ... -1259. -1257. -1256.]
 [-1613. -1624. -1627. ... -1260. -1260. -1259.]
 [-1624. -1635. -1637. ... -1261. -1262. -1261.]]

5x5 Kernel with 2x2 Stride:
 [[-1263. -1259. -1249. ... -2526. -2516. -2508.]
 [-1268. -1257. -1244. ... -2538. -2516. -2509.]
 [-1274. -1276. -1269. ... -2535. -2521. -2503.]
 ...
 [-1560. -1574. -1601. ... -1308. -1254. -1246.]
 [-1583. -1595. -1620. ... -1290. -1260. -1255.]
 [-1613. -1627. -1639. ... -1275. -1261. -1260.]]
