In [1]:
import numpy as np

In [2]:
def convolution(matrix, kernel):
    row = matrix.shape[0] - len(kernel) + 1
    col = matrix.shape[1] - len(kernel[0]) + 1
    filtered_matrix = np.zeros(shape=(row, col))
    for i in range(row):
        for j in range(col):
            current = matrix[i:i + len(kernel), j:j + len(kernel[0])]
            multiplication = np.sum(current * kernel)
            filtered_matrix[i, j] = multiplication
    return filtered_matrix

In [3]:
# Define a 5x5 matrix for demonstration
matrix = np.array([[1, 2, 3, 4, 5],
                   [6, 7, 8, 9, 10],
                   [11, 12, 13, 14, 15],
                   [16, 17, 18, 19, 20],
                   [21, 22, 23, 24, 25]])

# Define a kernel for convolution
kernel = np.array([[-1, -1, -1],
                   [-1, 0, -1],
                   [-1, -1, -1]])

In [4]:

filtered_matrix = convolution(matrix, kernel)

print(filtered_matrix)

[[ -56.  -64.  -72.]
 [ -96. -104. -112.]
 [-136. -144. -152.]]
