In [13]:
import numpy as np

In [14]:
def convolution(matrix, kernel, stride=(1, 1)):
    # Calculating the dimensions of the output matrix
    row = (matrix.shape[0] - kernel.shape[0]) // stride[0] + 1
    col = (matrix.shape[1] - kernel.shape[1]) // stride[1] + 1
    filtered_matrix = np.zeros(shape=(row, col))
    
    # Looping through the matrix with the given stride
    for i in range(0, row * stride[0], stride[0]):
        for j in range(0, col * stride[1], stride[1]):
            # Ensuring the kernel fits within the matrix boundaries
            current = matrix[i:i + kernel.shape[0], j:j + kernel.shape[1]]
            multiplication = np.sum(current * kernel)
            filtered_matrix[i // stride[0], j // stride[1]] = multiplication
    
    return filtered_matrix

In [15]:
# Defining a 9x9 matrix with random values
matrix = np.random.randint(0, 100, size=(9, 9))
print("Input Matrix:\n", matrix)

# Defining a 3x3 kernel for demonstration
kernel_3x3 = np.array([[-1, -1, -1],
                       [-1, 0, -1],
                       [-1, -1, -1]])

# Defining a 5x5 kernel for demonstration
kernel_5x5 = np.array([[-1, -1, -1, -1, -1],
                       [-1, -1, -1, -1, -1],
                       [-1, -1, 0, -1, -1],
                       [-1, -1, -1, -1, -1],
                       [-1, -1, -1, -1, -1]])

Input Matrix:
 [[62  0 41 38 46 80 64 21 13]
 [74 28  8 12  8 15  6 28 48]
 [33 40 80  3 27 20 25 77 36]
 [58 54 22 22 74 56 72 92 48]
 [13 54 49 57 68 49 49 41 73]
 [31 52 87 67 68  9 96 63 75]
 [82 46 48 92 33 93 58 22 24]
 [26 40 28 65 45 81  0 27 14]
 [18 19 48 22 15 21 52 82 99]]


In [16]:

# Performing convolution with a stride of 1x1
filtered_matrix_3x3_stride_1 = convolution(matrix, kernel_3x3, stride=(1, 1))
print("3x3 Kernel with 1x1 Stride:\n", filtered_matrix_3x3_stride_1)
print()

# Performing convolution with a stride of 2x2
filtered_matrix_3x3_stride_2 = convolution(matrix, kernel_3x3, stride=(2, 2))
print("3x3 Kernel with 2x2 Stride:\n", filtered_matrix_3x3_stride_2)
print()

# Performing convolution with a stride of 1x1
filtered_matrix_5x5_stride_1 = convolution(matrix, kernel_5x5, stride=(1, 1))
print("5x5 Kernel with 1x1 Stride:\n", filtered_matrix_5x5_stride_1)
print()

# Performing convolution with a stride of 2x2
filtered_matrix_5x5_stride_2 = convolution(matrix, kernel_5x5, stride=(2, 2))
print("5x5 Kernel with 2x2 Stride:\n", filtered_matrix_5x5_stride_2)

3x3 Kernel with 1x1 Stride:
 [[-338. -242. -251. -241. -276. -330. -290.]
 [-357. -189. -253. -210. -283. -366. -355.]
 [-349. -359. -380. -302. -384. -409. -421.]
 [-366. -415. -457. -402. -492. -478. -568.]
 [-410. -465. -502. -468. -514. -384. -438.]
 [-394. -477. -441. -520. -390. -391. -357.]
 [-315. -380. -331. -422. -317. -436. -351.]]

3x3 Kernel with 2x2 Stride:
 [[-338. -251. -276. -290.]
 [-349. -380. -384. -421.]
 [-410. -502. -514. -438.]
 [-315. -331. -317. -351.]]

5x5 Kernel with 1x1 Stride:
 [[ -891.  -948.  -964. -1030. -1111.]
 [-1067. -1007.  -975. -1048. -1151.]
 [-1211. -1213. -1256. -1284. -1299.]
 [-1194. -1292. -1320. -1390. -1234.]
 [-1125. -1164. -1267. -1182. -1199.]]

5x5 Kernel with 2x2 Stride:
 [[ -891.  -964. -1111.]
 [-1211. -1256. -1299.]
 [-1125. -1267. -1199.]]
