In [1]:
import cv2 as cv
import numpy as np

In [2]:
def  convolution(img, kernel):
  row = img.shape[0] - len(kernel) + 1
  col = img.shape[1] - len(kernel[0]) + 1
  filtered_img = np.zeros(shape = (row, col))
  for i in range (row):
    for j in range(col):
      current = img[i : i + len(kernel), j : j + len(kernel[0])]
      multiplication = np.sum(current * kernel)
      filtered_img[i, j] = multiplication
  return filtered_img

In [3]:

img = cv.imread("images/0b7fabe7ec7df752e59ca8c019bae095_hd-964005064.jpg")
gray_img = cv.cvtColor(img, cv.COLOR_BGR2GRAY)
kernel = [[-1,-1,-1], [-1,0,-1],[-1,-1,-1]]

filtered_img = convolution(gray_img, kernel)
cv.imshow("original img", img)
cv.imshow("Gray img", gray_img)
cv.imshow("filtered img", filtered_img)
print(filtered_img)
cv.waitKey(0)


[[-1728. -1728. -1728. ... -1152. -1152. -1152.]
 [-1731. -1731. -1731. ... -1155. -1155. -1155.]
 [-1733. -1733. -1733. ... -1157. -1157. -1157.]
 ...
 [-1401. -1381. -1360. ...  -412.  -414.  -415.]
 [-1352. -1333. -1313. ...  -392.  -396.  -398.]
 [-1300. -1281. -1263. ...  -378.  -383.  -388.]]
